apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo
type: Opaque
stringData:
  # Variables sensibles exigees au demarrage.
  DB_NAME: CHANGE_ME
  DB_USER: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
